name: Node.js Package

on:
  release:
    types: [created]

jobs:
  send-sms:
    name: Send SMS
    runs-on: ubuntu-latest
    steps:
    - name: 'Sending SMS Notification'
      uses: twilio-labs/actions-sms@v1
      with:
          senderid: ${{ secrets.senderid }}
          toPhoneNumber: '+1(234)3334444'
          message: 'Hello from Twilio'
      env:
          SMSALERT_USERNAME: ${{ secrets.SMSALERT_USERNAME }}
          SMSALERT_PASSWORD: ${{ secrets.SMSALERT_PASSWORD }}
