name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: sagarchoudhary96/exosms-actions@v1
        with:
          fromPhoneNumber: '09513886363'
          toPhoneNumber: '7828856652'
          message: 'The latest version of your package has been shipped 🎉'
        env:
         EXOTEL_ACCOUNT_SID: ${{ secrets.EXOTEL_ACCOUNT_SID }}
         EXOTEL_API_KEY: ${{ secrets.EXOTEL_API_KEY }}
         EXOTEL_API_TOKEN: ${{ secrets.EXOTEL_API_TOKEN }}
