name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: brijkishor7828/smsalert@v1
        with:
          senderid: ${{ secrets.SMSALERT_SENDERID }}
          toPhoneNumber: ${{ secrets.MY_PHONE_NUMBER }}
          message: 'The latest version of your package has been shipped 🎉'
        env:
         SMSALERT_USERNAME: ${{ secrets.SMSALERT_USERNAME }}
         SMSALERT_PASSWORD: ${{ secrets.SMSALERT_PASSWORD }}
