name: Node.js Package

on:
  release:
    types: [created]

jobs:
  send-sms:
    name: Send SMS
    runs-on: ubuntu-latest
    steps:
    - name: 'Sending SMS Notification'
      uses: brijkishor7828/smsalert@master
      env:
        SMSALERT_USERNAME: ${{ secrets.SMSALERT_USERNAME }}
        SMSALERT_PASSWORD: ${{ secrets.SMSALERT_PASSWORD }}
      with:
        senderid: ${{ secrets.senderid }}
        recipientNumber: ${{ secrets.RECIPIENT_NUMBER }}
        message: "New push on ${{ github.repository }} from ${{ github.actor }}"
  
