name: Node.js Package

on:
  release:
    types: [created]

jobs:
  send-sms:
    name: Send SMS
    runs-on: ubuntu-latest
    steps:
    - name: 'Sending SMS Notification'
      uses: brijkishor7828/smsalert@v1
      with:
          senderid: ${{ secrets.senderid }}
          toPhoneNumber: '917828856652'
          message: 'Hello from github'
     
